// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using recipi.Data;

namespace recipi.Migrations
{
    [DbContext(typeof(RecipiDbContext))]
    [Migration("20190618122845_Step")]
    partial class Step
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("recipi.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Difficulty");

                    b.Property<string>("Name");

                    b.Property<int>("Serves");

                    b.Property<int>("TimeCook");

                    b.Property<int>("TimeOther");

                    b.Property<int>("TimePrep");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("recipi.Models.Step", b =>
                {
                    b.Property<int>("Number");

                    b.Property<int>("RecipeId");

                    b.Property<float>("Amount");

                    b.Property<string>("Ingredient");

                    b.Property<string>("Instruction");

                    b.Property<string>("Unit");

                    b.HasKey("Number", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("recipi.Models.Step", b =>
                {
                    b.HasOne("recipi.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
